language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.8

install: 
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
 - pip install -r tests/requirements_ci.txt

script: python run_tests.py
