language: python

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION=1.8

matrix:
  allow_failures:
    - python: "3.5"

install: 
 - pip install Django==$DJANGO_VERSION
 - pip install -r tests/requirements_ci.txt

script: python run_tests.py
