FAST_PYTHON_DATA = {'response': {'docs': [{'auth': 'Python (Computer program language)',
    'idroot': 'fst01084736',
    'suggestall': ['Python (Computer program language)'],
    'type': 'auth'},
   {'auth': 'Pythons',
    'idroot': 'fst01084738',
    'suggestall': ['Pythons'],
    'type': 'auth'},
   {'auth': 'Pythons',
    'idroot': 'fst01084738',
    'suggestall': ['Pythonidae'],
    'type': 'alt'},
   {'auth': 'Pythons',
    'idroot': 'fst01084738',
    'suggestall': ['Pythoninae'],
    'type': 'alt'},
   {'auth': 'Monty Python (Comedy troupe)',
    'idroot': 'fst00530439',
    'suggestall': ['Monty Python (Comedy troupe)'],
    'type': 'auth'},
   {'auth': 'Monty Python (Comedy troupe)',
    'idroot': 'fst00530439',
    'suggestall': ["Monty Python's Flying Circus (Comedy troupe)"],
    'type': 'alt'},
   {'auth': 'Monty Python (Comedy troupe)',
    'idroot': 'fst00530439',
    'suggestall': ['Pythons (Comedy troupe)'],
    'type': 'alt'},
   {'auth': "Monty Python's flying circus (Television program)",
    'idroot': 'fst01391357',
    'suggestall': ["Monty Python's flying circus (Television program)"],
    'type': 'auth'},
   {'auth': 'Mosasauridae',
    'idroot': 'fst01026727',
    'suggestall': ['Pythonomorpha'],
    'type': 'alt'},
   {'auth': 'Pythons as pets',
    'idroot': 'fst01084740',
    'suggestall': ['Pythons as pets'],
    'type': 'auth'}],
  'numFound': 45,
  'start': 0},
 'responseHeader': {'QTime': 94,
  'params': {'fl': 'idroot,auth,type,suggestall', 'q': 'suggestall:python'},
  'status': 0}}

FAST_NO_RESULTS_DATA = {'response': 
                            {'docs': [], 'numFound': 0, 'start': 0},
                        'responseHeader':
                            {'QTime': 71,
                             'params': 
                                {'fl': 'idroot,auth,type,suggestall',
                                 'q': 'suggestall:python01234'},
                             'status': 0}
                       }
