# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etd_app', '0007_auto_20160804_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
