# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etd_app', '0008_auto_20180103_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='bdr_collection_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
