# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etd_app', '0009_auto_20180419_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='private_access_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
