# Generated by Django 3.2.10 on 2021-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etd_app', '0011_auto_20200212_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='bdr_collection_pid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
